"""auth_added

Revision ID: 77d003e61977
Revises: ef3a4c329d7d
Create Date: 2026-04-05 19:10:47.558277

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d003e61977'
down_revision: Union[str, None] = 'ef3a4c329d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=True)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
