"""init

Revision ID: ef3a4c329d7d
Revises: 
Create Date: 2026-04-05 18:22:07.226405

"""
from typing import Sequence, Union
from alembic import op
import sqlmodel
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ef3a4c329d7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorydefault')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorydefault',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('categorydefault_pkey'))
    )
    # ### end Alembic commands ###
